# Generated by Django 4.0.5 on 2023-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pers_identifier',
            field=models.CharField(default='delete', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='secure_number',
            field=models.CharField(default='delete', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
