# Generated by Django 4.0.5 on 2023-10-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphotos',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='userphotos',
            name='photo3',
        ),
    ]
