# Generated by Django 4.0.5 on 2023-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userphotos_photo2_remove_userphotos_photo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphotos',
            name='photo1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
