# Generated by Django 4.0.5 on 2023-10-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userphotos_photo1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphotos',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userphotos',
            old_name='photo1',
            new_name='user_photo',
        ),
    ]
