# Generated by Django 4.0.5 on 2023-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userphotos_photo_pers_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResultPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo_first', models.ImageField(upload_to='result_foto/')),
                ('user_photo_second', models.ImageField(upload_to='result_foto/')),
                ('date_upload', models.DateField()),
                ('preview_result', models.CharField(max_length=255)),
                ('result_view', models.TextField()),
                ('photo_pers_identifier', models.CharField(max_length=255)),
                ('photo_secure_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pers_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='secure_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='photo_pers_identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='photo_secure_number',
            field=models.CharField(max_length=255),
        ),
    ]
