# Generated by Django 4.0.5 on 2023-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userresultphotos_alter_useraccount_pers_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresultphotos',
            name='user_photo_first',
            field=models.ImageField(upload_to='images/result_foto/'),
        ),
        migrations.AlterField(
            model_name='userresultphotos',
            name='user_photo_second',
            field=models.ImageField(upload_to='images/result_foto/'),
        ),
    ]
