# Generated by Django 4.0.5 on 2023-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userresultphotos_user_photo_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresultphotos',
            name='user_photo',
            field=models.ImageField(default=2, upload_to='images/pred_result/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userresultphotos',
            name='user_photo_first',
            field=models.ImageField(upload_to='images/result_photo/'),
        ),
        migrations.AlterField(
            model_name='userresultphotos',
            name='user_photo_second',
            field=models.ImageField(upload_to='images/result_photo/'),
        ),
    ]
