# Generated by Django 4.0.5 on 2023-10-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userresultphotos_user_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresultphotos',
            name='user_photo',
        ),
    ]
