# Generated by Django 4.0.5 on 2023-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userresultphotos_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotos',
            name='date_upload',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
