# Generated by Django 4.0.5 on 2024-02-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userphotos_date_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemPhoto', models.ImageField(upload_to='images/')),
                ('shortName', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('sale', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('haracteristic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userphotos',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='UserResultPhotos',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='pers_identifier',
            new_name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='secure_number',
        ),
        migrations.DeleteModel(
            name='UserPhotos',
        ),
        migrations.AddField(
            model_name='userbuy',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
