# Generated by Django 4.0.5 on 2024-02-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_itemphoto_userbuy_remove_userphotos_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='haracteristic',
            field=models.TextField(),
        ),
    ]
