# Generated by Django 4.0.5 on 2024-02-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_itemphoto_haracteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='arivel',
            field=models.CharField(default='', max_length=255),
        ),
    ]
