# Generated by Django 4.0.5 on 2024-02-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_itemphoto_arivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuy',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
